language: node_js

node_js:
  - 'stable'
  - '4'
  - '5'

sudo: false

before_install:
  - npm install -g typings
  - npm install -g codeclimate-test-reporter

after_script:
  - codeclimate-test-reporter < coverage/lcov.info
  - node_modules/.bin/coveralls < coverage/lcov.info

deploy:
  provider: npm
  email: 'devmonk@mediamonks.com'
  api_key:
    secure: 'nkyQm7A/0DDvmDlL4eFOfUmeMb1oBCoyIrCBnha1JbCtWLGEm2G5F9gDEymXGqHSckV00kmUVDDtu9W+HZfAeSq1B54raODjOzXKSKSCuW4GsdeFZcwa4MjcQ7Pl/DKzvmSopTfdEnJ1EbUKplepeeIsm/5yLQyoF1YgJNW8O3lpjk6uYc2tORYTTbF9qGisGr0sU7eljLyNT6oN9zNsDDH9KkAjynetrRe0uugPtnabolgDDZETmRnh9AslngPjp5iT8JQy7eDOFD4RsRzKcLIsp03+z+N3T7UqujrdfJ7xFtGHj7nQD9cFzD1D3dYnYxTnUVnXCyrPUbRu7F0R1ECrdHsNuIucP3cFjhFIKX8gOvXSLSfc9v/eZ/2iU7/aURSONhTmYU+pWSJpuVkmM+HWGOHdj4EwkTeuWIkKHGPdcoyhW6fTOGFnHmD999PnFpxTeRCBo58Muqb7sKAjaLoIwGl8P4ZLTPzt50n2B3iezPCDwdLZJQEDDKUc4bZGW3VYlL9l/nk9WPTsUkCRsIs3gVeE+22e5+3rArpstZGi6rT3TdjEuhg9PeHq5kvAKr6ByGOO9PqLLaVRq1N8dQ8Igbc5gc0utURVXlvyvdp00wwSiPRQNtODX7JE8RAr1IF+Pfq88sGp0WGk4mK1Rtk0ewzOlPpcSTiNyc2RXfE='
  on:
    tags: true
    node: '4'
  skip_cleanup: true

addons:
  code_climate:
    repo_token:
      secure: 'jMib2LNFGzfKiINRK0fOwibNgHnizTh87Fb1YK0Q2UpWtF7WiigEBhNyiX3pF02HH3iRuICHKYzE1QrZbIzk88XVTUhilO7vI+h1VpgbcuOxq7nkE+kSfxAiTpkD6eY7c0s8wSViKTPOVPPrpRfp8RYYLx6Vcox9jlN7StOHAgDuiwGwHPZ6lz2KGzX1xx8Z8ZLnHIIihv7rqQgetu7BNoPcrPv2Dz63qZI3DbFPWVJIe05B6I7iuiPgzlRZzIvUWofpp6zM5jT9ktrGyF786sh15mDzixoDzUDKmw6ptbc7MeoEuT2Co7FYr4LibXClSaoXcfKJ37/6E5Xzya1e7Sz/83+H1Xi34LCUcVHySzmCWSMWa1fGnZMCHJUdhCVmY5EJMQSGJEvPwHt+1beRYsWAm0cP2RsZ3LhIj9uB6jVXUz1pmhlkL2AFiuBZ2D3vKw4DTtnKqBounsI/FFm0Z0bhsOfkUs7HzAtdnPGjkzlHYW//YvncmTaO0fnMswJVLTKlMq9J/VnqLF1bH2CVYO9zBXIvf786SwgNrWAW/nmyOHE0kOzo79OVfm147qTPmF93ajwLWA814HUK8xpPZ5nMLgFaPpqlNO8co/5gpGm3cRrxRQ2yeOMCealz/EVJYS9LUmYugR42Ayg6iHLRoqwCKdtsjhMFZNEAOwsMs80='
